LETTERS_ENGLISH = 'abcdefghijklmnopqrstuvwxyz'
LETTERS_RUSSIAN = 'абвгдеёжзийклмнопрстуфхцчшщьъэюя'
DIGITS = '0123456789'
SPECIALS = '_-'
LEGAL_SYMBOLS = LETTERS_ENGLISH + LETTERS_RUSSIAN + DIGITS + SPECIALS

LEGAL_SYMBOLS_SET = set(LEGAL_SYMBOLS)